name: simple_lists
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  gestures: ^1.0.0
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  provider: ^6.0.3
  device_info_plus: ^11.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
